name: z_delivery_man
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # State Managment
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3

  # for Easily make Flutter apps responsive. Automatically adapt UI to different screen
  sizer: ^2.0.13

  # is open source library that come with pre-build 1000+ UI components
  getwidget: ^3.1.1

  # Brings HexColor for your dart and flutter projects, convert material colors to hex colors
  hexcolor: ^3.0.1

  # for reading and writing simple key-value pairs (Local Caching)
  shared_preferences: ^2.2.0

  # HTTP networking package
  dio: ^5.3.0

  # Enabling connecting to multiple Firebase apps.
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.16
  # firebase_storage: ^11.5.6
  firebase_app_check: ^0.2.1+14

  # For integrating Google Maps in iOS and Android applications.
  # google_maps_flutter: ^2.5.1
  google_maps_flutter: ^2.5.3

  # for easy access to device's location in real-time.
  location: ^6.0.0

  # This plugin provides a cross-platform (iOS, Android) API for generic location (GPS etc.) functions.
  geolocator: ^9.0.2

  # Easily create toast message.
  fluttertoast: ^8.2.2

  # an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0

  # for launching a URL. Supports web, phone, SMS, and email schemes.
  url_launcher: ^6.1.12

  # to find available maps installed on a device and launch them with a marker or show directions.
  map_launcher: ^2.5.0+1

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.7

  # Powerful package to create beautiful custom animations in no time.
  simple_animations: ^5.0.2

  # The Font Awesome Icon pack available as Flutter Icons. Provides 2000 additional icons to use in your apps.
  font_awesome_flutter: ^10.5.0

  # for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: ^1.0.5

  # Show UI elements according for conditional type and supports null safety
  conditional_builder_null_safety: ^0.0.6

  # to create dashed lines. - - - - - - -
  fdottedline_nullsafety: ^2.0.1

  # to use fonts from fonts.google.com. Supports HTTP fetching, caching, and asset bundling.
  google_fonts: ^6.1.0

  # for drawing over images. Supports color, strokeWidth, different paintModes and exporting image.
  image_painter: ^0.7.1

  # for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.1.1
  
  # A string-based path manipulation library. All of the path operations you know and love, 
  path: ^1.8.2


  # Bar indicator made of a series of selected and unselected steps
  step_progress_indicator: ^1.0.2

  # easy to use and extensible logger which prints beautiful logs.
  logger: ^1.2.0
  pretty_dio_logger: ^1.3.1
  # flutter_screenutil: ^5.9.3

  

  # Local Plugin From (Ahmed Sami)
  # my_ui:
  #   path: /Users/mercadoegypt/Documents/my_ui

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
